name: Build immortalwrt image
on:
  workflow_dispatch:
    inputs:
      wrt_version:
        description: "选择immortalwrt版本"
        required: true
        type: choice
        options:
          - 25.12.0
          - 25.12.1
          - 25.12.2
      fs_size:
        description: '选择文件系统大小'
        required: true
        type: choice
        default: '2048'
        options:
          - '1024'
          - '2048'
          - '3072'
          - '4096'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/build.sh

      - name: Build ImmortalWrt-x86-64-efi 25.12.x
        run: |
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/build.sh:/home/build/immortalwrt/build.sh" \
            -e ROOTFS_SIZE=${{ github.event.inputs.fs_size }}
          immortalwrt/imagebuilder:x86-64-openwrt-${{ github.event.inputs.wrt_version }} /bin/bash /home/build/immortalwrt/build.sh

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Autobuild-x86-64
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*ext4-combined-efi.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}